In [1]:
#Импорт библиотеки NumPy с общепринятым сокращением
import numpy as np

#Примеры создания массивов: из обычных списков
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [2]:
#с использованием функций `zeros`, `ones`, `arange` или аналогичных
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(1, 5, 0.2)

print(a, '\n', b, '\n', c, '\n', d, '\n')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8] 



In [3]:
#Демонстрация атрибутов: вывод формы (shape) и типа данных (dtype) для одного из массивов
A = np.random.random((3, 5, 15))

print("Форма:", A.shape)
print("Тип данных:", A.dtype)
print("Размер:", A.size)

Форма: (3, 5, 15)
Тип данных: float64
Размер: 225


In [4]:
#Примеры индексирования и срезов: получение отдельного элемента, извлечение подмассива с помощью среза
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])

print("Массив со второго элемента до конца")
print(x[1:])
print("Перевернутый массив")
print(x[::-1])
print("Элементы с второго по третий включительно")
print(x[2:4])
print("Только первые значения в паре")
print(x[:, 0])

Массив со второго элемента до конца
[[ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
Перевернутый массив
[[ 9 10]
 [ 7  8]
 [ 5  6]
 [ 3  4]
 [ 1  2]]
Элементы с второго по третий включительно
[[5 6]
 [7 8]]
Только первые значения в паре
[1 3 5 7 9]


In [5]:
#5. Примеры векторных операций и базовых статистик:
# - поэлементное сложение или умножение массивов;
# - вычисление средней величины (`mean`) или другой простой статистики.

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# сложение
c = a + b
print("Сложение:", c)

# поэлементное умножение
d = a * b
print("Умножение:", d)

# умножение на число
e = a * 2
print("Умножение на 2:", e)

Сложение: [11 22 33 44 55]
Умножение: [ 10  40  90 160 250]
Умножение на 2: [ 2  4  6  8 10]


In [6]:
N = np.array([5, 10, 15, 20, 25])

# среднее арифметическое
mean_value = np.mean(N)
print("Среднее:", mean_value)

std_dev = np.std(N)
print("Стандартное отклонение:", std_dev)

Среднее: 15.0
Стандартное отклонение: 7.0710678118654755
